language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - python -m unittest discover -s tests -t tests
deploy:
  provider: pypi
  user: "techlee"
  password:
    secure: "Your encrypted password"
  on:
    tags: true
